### ISSUE TITLE
a18_acid typo

### ISSUE THREAD

**Issue by ryxen** [mdaeron/InterCarb#1]
In InterCarb.py on the line 373:
a18acid = exp(3.59 / (acid_T + 273.15) - 1.79e-3)
This is a typo, right? So the computations for acid temperature 70 are not valid?

**Comment by mdaeron** [comment]
Good catch, thanks! Corrected in [#53b8c2](https://github.com/mdaeron/InterCarb/commit/53b8c2c9a1fef79f55e80a900758f81fc40b9177).

Fortunately, because working gas composition is computed based on the ETH standards and the same (wrong, in this case) value of `a18_acid`, the only effect on Figure 2 is that labs B and D are very slightly offset. The average values are not affected at the 0.0001 ‰ level.

Thanks again.
